services:
  frontend:
    image: recipes-frontend:latest
    container_name: recipes-frontend
    environment:
      HOSTNAME:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_SERVER_URL: https://pet-food-recipes.ru
        NEXT_PUBLIC_STATIC_SERVER_URL: https://s3.twcstorage.ru
        NEXT_PUBLIC_BUCKET_AVATARS: a7cada3e-avatars
        NEXT_PUBLIC_YANDEX_METRIKA_ID: 99654607
      no_cache: true
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
