'use client';
import { ReactNode, useState } from 'react';
import { Roboto } from 'next/font/google';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import '@/styles/globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  const [queryClient] = useState(new QueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="ru">
        <body className={roboto.variable}>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
