import { ReactNode } from 'react';
import { Roboto } from 'next/font/google';

import './globals.css';

const roboto = Roboto({ variable: '--font-roboto', weight: ['100', '300', '400', '500', '700', '900'], subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ru">
      <body className={roboto.variable}>{children}</body>
    </html>
  );
}
